#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$PATH:/usr/lib/lightdm/lightdm:/usr/texbin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:$HOME/bin:$HOME/code/tools/dev
export PATH=/usr/local/bin:$PATH

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
export CDPATH=$CDPATH:$HOME/code:$HOME/code/gems:$HOME/code/java:$HOME/code/java/hanuman:$HOME/code/java/seamstress:$HOME/code/java/componada:$HOME/code/java/

# Use nicer dircolors
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
eval `dircolors -b ~/.dircolors`
alias ls="ls --color=always --group-directories-first"
alias tmux="tmux -u"
alias e="/usr/local/Cellar/emacs/24.4/bin/emacsclient --no-wait"
alias emacs="/usr/local/Cellar/emacs/24.4/bin/emacs -nw"
alias bi="bundle install"
alias be="bundle exec"
alias gst="git status"
alias gco="git checkout"
alias si="say -v nora"
# More color with grc (brew install grc)
#source "`brew --prefix`/etc/grc.bashrc"


# docker stuff
#export DOCKER_HOST=tcp://192.168.59.103:2375
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/jonas/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

$(boot2docker shellinit)
docker-ip() {
    boot2docker ip 2> /dev/null
}


# Load rbenv automatically by adding
# the following to ~/.zshrc:
eval "$(rbenv init -)"
export JAVA_HOME=$(/usr/libexec/java_home)
# To avoid irritating java launchers
export _JAVA_OPTIONS=-Djava.awt.headless=true

export EDITOR="emacsclient"

# Don't exit on ctrl-d
set -o ignoreeof

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
